services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data       # persists bot.db across restarts
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - DATA_DIR=/app/data
      - FFMPEG_EXECUTABLE=ffmpeg
      - REDIS_URL=redis://:a3dbdb2248225f3658fb1f0e679f5bf912240bcaed632034@192.168.1.36:6379
    env_file:
      - .env
